{{- if .Values.jmxExporter.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "java-app.fullname" . }}-jmx-config
  labels:
    {{- include "java-app.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.jmxExporter.config | nindent 4 }}
{{- end }} 