apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-app.fullname" . }}
  labels:
    {{- include "java-app.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.app.port.service }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.jmxExporter.enabled }}
    - port: {{ .Values.jmxExporter.port }}
      targetPort: jmx-metrics
      protocol: TCP
      name: jmx-metrics
    {{- end }}
    {{- with .Values.service.additionalPorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "java-app.selectorLabels" . | nindent 4 }} 